### ISSUE TITLE
plugin not work after update11-20-19

### ISSUE THREAD

**Issue by juicycookies** [alliedmodders/cssdm#12]
the plugin not work after the latest update, server runs with sourcemod 1.10, metamod 1.10.7, and os linux, please help fix and update cssdm plugin.
https://forums.alliedmods.net/showthread.php?t=316592

**Comment by kilroy98** [comment]
@Drifter321 need your help

**Comment by maribeiro** [comment]
Yup, @Drifter321 it's not working...

**Comment by JustZerooo** [comment]
@Drifter321 YYou need get paid or why not anymore update here?

**Comment by Headline** [comment]
What other information has been given other than “it’s not working”

Load it manually by doing `sm exts load` and paste the output please

**Comment by JustZerooo** [comment]
Dafuq?

**Comment by Headline** [comment]
It could need gamedata, a rebuild, some other more invasive changes, and I may be able to fix it if I knew what it needed. I’m currently on holiday and have no idea what the issue is so the more information the better

**Comment by JustZerooo** [comment]
```log
L 12/24/2019 - 20:28:50: SourceMod error session started
L 12/24/2019 - 20:28:50: Info (map "de_mirage") (file "/home/csgoserver/serverfiles/csgo/addons/sourcemod/logs/errors_20191224.log")
L 12/24/2019 - 20:28:50: [SM] Unable to load extension "cssdm.ext": Could not find signature "CSWeaponDrop"
L 12/24/2019 - 20:28:50: [SM] Unable to load plugin "cssdm/dm_equipment.smx": Required extension "CS:S DM" file("cssdm.ext") not running
L 12/24/2019 - 20:28:50: [SM] Unable to load plugin "cssdm/dm_basics.smx": Required extension "CS:S DM" file("cssdm.ext") not running
L 12/24/2019 - 20:28:50: [SM] Unable to load plugin "cssdm/dm_spawn_protection.smx": Required extension "CS:S DM" file("cssdm.ext") not running
L 12/24/2019 - 20:28:50: [SM] Unable to load plugin "cssdm/dm_preset_spawns.smx": Required extension "CS:S DM" file("cssdm.ext") not running
L 12/24/2019 - 20:28:50: [SM] Unable to load plugin "cssdm/dm_bot_quotas.smx": Required extension "CS:S DM" file("cssdm.ext") not running
L 12/24/2019 - 20:28:50: [SM] Unable to load plugin "upgrades/smrpg_upgrade_speed.smx": Required extension "dhooks" file("dhooks.ext") not running
```

I changed the signature after searching : 
```h
"linux"            "\x55\x89\xE5\x57\x56\x53\x81\xEC\x00\x00\x00\x00\x8B\x45\x08\x0F\xB6\x5D\x14"
```
After cheking into IDA

![#](https://i.imgur.com/HhJaJ6g.png)

**Comment by asherkin** [comment]
You have the wrong binary open in IDA - CS:GO's Linux server bins do not have symbols.

**Comment by JustZerooo** [comment]
Yep. I changed ti the correct one but signatur not working because need some more changes.

**Comment by Headline** [comment]
I’m assuming the parameters to the target function has changed

**Comment by Sh4d0w0561** [comment]
Same problem here, server is crashing, when cssdm was loaded. If cssdm disabled, server not crashing anymore and work fine. We need a update for cssdm. Thanks!

Btw: Merry christmas and happy new year!

**Comment by JustZerooo** [comment]
https://forums.alliedmods.net/showthread.php?t=190785&page=22

Updated!

**Comment by Sh4d0w0561** [comment]
Will there be a new snapshot for cssdm?  Because no new one is available yet.

**Comment by Headline** [comment]
Yes, buildbot needs some tweaks for sourcemod 1.10 compilation but I’ll take a look tomorrow and then finish patch #13 if it’s not done by then so we can get this out

**Comment by Headline** [comment]
Should be fixed, please refer to the following builds and let me know if all is well
```
  | cssdm-2.1.6-git268-linux.tar.gz | 29-Dec-2019 14:03 | 367K
  | cssdm-2.1.6-git268-windows.zip | 29-Dec-2019 14:03 | 348K
  | cssdm-2.1.6-git268-mac.zip | 29-Dec-2019 14:02 | 229K
````

**Comment by Killer0561** [comment]
Thank you very much! Will test it today and give Feedback later. Will edit my post then.

**Comment by Sh4d0w0561** [comment]
Thanks. Work perfect! Problem was solved. Thx for the quick fix.
