### ISSUE TITLE
server crash due to respawn the player before it is ingame

### ISSUE THREAD

**Issue by PresidentEvil** [alliedmodders/cssdm#2]
Metamod:Source version 1.10.5
SourceMod Version: 1.7.3-dev+5232

ACCELERATOR:

Stack Trace
Function
0 server.so!CCSGameRules::IsSpawnPointValid(CBaseEntity, CBasePlayer) + 0x24
1 server.so!CCSPlayer::SelectSpawnSpot(char const, CBaseEntity&) + 0x19c
2 server.so!CCSPlayer::EntSelectSpawnPoint() + 0x318
3 server.so!CCSGameRules::GetPlayerSpawnSpot(CBasePlayer) + 0x17
4 server.so!CBasePlayer::Spawn() + 0x2d1
5 server.so!CCSPlayer::Spawn() + 0xa1
6 server.so!CCSPlayer::RoundRespawn() + 0xa3
7 0xee5029c3
8 bintools.ext.so!CallWrapper::Execute(void, void*) [CallWrapper.cpp:128 + 0xa]
9 cssdm.ext.2.csgo.so + 0x16580

another crash:

Stack Trace
Function
0 server.so!CCSGameRules::IsSpawnPointValid(CBaseEntity, CBasePlayer) + 0x24
1 server.so!CCSPlayer::SelectSpawnSpot(char const, CBaseEntity&) + 0x19c
2 server.so!CCSPlayer::EntSelectSpawnPoint() + 0x318
3 server.so!CCSGameRules::GetPlayerSpawnSpot(CBasePlayer) + 0x17
4 server.so!CBasePlayer::Spawn() + 0x2d1
5 server.so!CCSPlayer::Spawn() + 0xa1
6 server.so!CCSPlayer::RoundRespawn() + 0xa3
7 0xecc189c3
8 bintools.ext.so!CallWrapper::Execute(void, void*) [CallWrapper.cpp:128 + 0xa]
9 cssdm.ext.2.csgo.so + 0x16580

The crash seems to come from cssdm. Trying to respawn the player before it is ingame.
I am using version cssdm-2.1.6-git217-linux.tar

**Comment by Drifter321** [comment]
This isn't related to cssdm, If the player wasnt valid it would crash much earlier, there is also already safety checks to make sure the client is on a valid team and in game. cssdm also doesnt change spawnpoint's it uses the built in ones then simply teleports players. It looks like the map has an invalid spawnpoint.
