### ISSUE TITLE
Error opening menu after switching teams.

### ISSUE THREAD

**Issue by Bobakanoosh** [alliedmodders/cssdm#4]
Hey! I use this plugin on a csgo server for the guns menu primarily, and an admin found this bug (seen in the video below).

https://www.youtube.com/watch?v=-vWFQvsn8_g

If you have the menu open when switching teams, it doesn't allow you to re-open it. I belive this would easily be solved by setting the g_bMenuEnabled[client] (or w/e it is) to false on team switch.

**Comment by Drifter321** [comment]
This should be fixed in the latest snapshot.
