### ISSUE TITLE
undefined symbol: CSSDM Crashes

### ISSUE THREAD

**Issue by Sh4d0w0561** [alliedmodders/cssdm#6]
Hello,

the latest snapshot cssdm for linux not work for me in Counter-Strike: Source. More Informations about this problem, in this thread:

https://forums.alliedmods.net/showthread.php?t=309932

[SM] Unable to load extension "cssdm.ext": /home/Server/gameserver/1-css-surfstyle/cstrike/addons/sourcemod/extensions/cssdm.ext.2.css.so: undefined symbol: _ZdlPvj

Metamod Snapshot: 1.10.7 - 966
Sourcemod Snapshot: 1.9.0 - 6251
CSSDM Snapshot: 2.1.6 - 253

Greeting, Killer0561

**Comment by Headline** [comment]
Thanks for creating this issue!

Drifter just rebuilt this against latest sdks, does the latest snapshot work okay for you now?

[cssdm-2.1.6-git254-linux.tar.gz](http://www.bailopan.net/cssdm/snapshots/2.1/cssdm-2.1.6-git254-linux.tar.gz)

**Comment by Sh4d0w0561** [comment]
yes, thanks for the fast replay!
snapshot cssdm-2.1.6-git254-linux work again for counter-strike: source servers.
tested and all work fine.

Greeting, Killer0561

**Comment by Headline** [comment]
Awesome, I'll go ahead and close this then.

Thanks
