### ISSUE TITLE
Cssdm not work csgo 

### ISSUE THREAD

**Issue by andrearre** [alliedmodders/cssdm#9]
The plugin cssdm not Work in csgo.

I use version 4 may 2019 6:44 http://www.bailopan.net/cssdm/snapsh...1-linux.tar.gz.

Please update this plugin errors:

L 06/17/2019 - 01:50:18: [SM] Unable to load extension "cssdm.ext": Could not find signature "DropWeapons"
L 06/17/2019 - 01:50:19: [SM] Unable to load plugin "cssdm\dm_basics.smx": Required extension "CS:S DM" file("cssdm.ext") not running
L 06/17/2019 - 01:50:19: [SM] Unable to load plugin "cssdm\dm_bot_quotas.smx": Required extension "CS:S DM" file("cssdm.ext") not running
L 06/17/2019 - 01:50:19: [SM] Unable to load plugin "cssdm\dm_equipment.smx": Required extension "CS:S DM" file("cssdm.ext") not running
L 06/17/2019 - 01:50:19: [SM] Unable to load plugin "cssdm\dm_preset_spawns.smx": Required extension "CS:S DM" file("cssdm.ext") not running
L 06/17/2019 - 01:50:19: [SM] Unable to load plugin "cssdm\dm_spawn_protection.smx": Required extension "CS:S DM" file("cssdm.ext") not running

**Comment by andrearre** [comment]
@Drifter321

**Comment by kilroy98** [comment]
Try to re-install signatures.

**Comment by andrearre** [comment]
> Try to re-install signatures.

as?

**Comment by kilroy98** [comment]
Re-upload to our server cssdm.games.txt

**Comment by andrearre** [comment]
I upload cssdm.games.txt ano not work 

I use SourceMod (1.10.0.6426) by AlliedModders 
Metamod 1.10.7 git 970 Linux

**Comment by andrearre** [comment]
> Re-upload to our server cssdm.games.txt

I upload cssdm.games.txt and not work

I use SourceMod (1.10.0.6426) by AlliedModders
Metamod 1.10.7 git 970 Linux

**Comment by Drifter321** [comment]
Should be fixed in latest snapshot
